### ISSUE TITLE
Potential Need for new lValue attribute in ableC

### ISSUE THREAD

**Issue by counc009** [melt-umn/ableC#111]
I'm working on a Tensor Algebra Compiler extension for ableC with Eric. I have an overload of function calls, and this is used to access elements from the tensor, but based on how the tensors are stored I have a situation where the forwarding code depends on whether the Expr appears as an lValue or rValue. The Expr nonterminal has an isLValue attribute, but this attribute doesn't behave as a check of whether the Expr is being used as an lValue or rValue. Such an attribute would have to be an inherited attribute, which is why such an attribute can't be added in an extension, as it causes MWDA analysis to fail. 

Eric asked me to create this so we can discuss whether this is something that should be added to the ableC, now that we have an example where this matters, or whether there is another known workaround. Thanks.

**Comment by krame505** [comment]
We definitely don't want to add more inherited attributes to `Expr`, since as you mentioned this would break a lot of things.  Also the design paradigm here is that we can construct any expression, and it tells us whether or not it can be an lvalue, which we then check further up the tree at the point in the expression where it matters.  

The way that this is intended to work is that in addition to overloading function call directly to perform an access, you would also provide an overload production for the combined expression of assigning to a function call.  We don't currently have a `getCallAssignOverloadProd` corresponding to this case, however it should be fairly easy to add - I can implement this if you decide to go this route.  
Alternatively, I would recommend overloading the array index syntax instead of function calls.  You can still get the same behavior of indexing on multiple comma-separated dimensions by pattern matching on the index looking for chained `commaExpr`s, and converting the result back to `Exprs` that you re-decorate as a local in your overload production.  Make sense?  

The only thing that is kinda broken with this is that taking the address of an expression isn't handled correctly as an overload for an lvalue, but that is kind of a corner case that will require a big refactor to fix properly.  Just a heads-up, I am planning on majorly redesigning how creating extension types and overloading works to make it a bit less weird, probably this fall.  Sorry for the confusion in the meantime.

**Comment by counc009** [comment]
Alright, thanks. I'll try overloading the array index syntax instead, it should work for my needs. Thanks again.
