### ISSUE TITLE
Initialization cannot be overloaded

### ISSUE THREAD

**Issue by counc009** [melt-umn/ableC#118]
In ableC's current implementation there is no method of overloading initialization. For example, working with tensors, I have a need to perform a deep copy, to prevent free'ing memory that is still available to another copy of the tensor. Currently, if a user were to want to perform such a copy, they would have to write:
```C
tensor t1 = ...setup t1...;
tensor t2 = {0};
t2 = t1;
```
(I use `{0}` to ensure that the values in the struct are zeroed)
With this, I overload equality in the statement `t2 = t1;`, and so can perform a deep copy. However, it seems like maybe we could have some way to overload initializing, so that `tensor t2 = t1;` could be used, and still perform the deep copy desired.

**Comment by krame505** [comment]
Hmm, thanks for reminding me - I had intended to figure out some way of dealing with this later on but never got around to it since this is kind of an ugly corner case.  But now I'm in the middle of re-spinning overloading and how extensions create new types once again, so I'll try to work something out.  

The fundamental issue here is that declarations in C are messy, and a single declaration can declare multiple things at once - so it isn't nice and easy to write an overload production into which something should transform, as is the case for e.g. `eqExpr :: (Expr ::= Expr Expr)`.  Another tricky thing is in dealing with global declarations - these must be initialized with a constant value, if initialized at all.  
We could maybe do something along the lines of:
* Allow initialization to be overloaded with a production of signature `(Stmt ::= Initializer Location)`
* Transform `declStmt`s containing an overloaded initializer with signature into a sequence of a non-initializing declaration and the initialization statement, for example
```
tensor t1 = t2;
```
becomes
```
tensor t1;
<copy t2 to t1>;
```
* Raise an error when an overloaded initializer occurs globally
* Potentially generate a default overload from the overload for assignment

However, a word of caution in your case: modifying initialization in this way could very easily lead to excess copy operations and memory leaks.  In your example, the line
```
tensor t1 = ...setup t1...;
```
would result in immediately copying the result of setting up `t1`, and throwing away the original, probably resulting in a memory leak.  C++ deals with these problems using move semantics and various kinds of smart pointers and references, but is extraordinarily complicated as a result and probably a path we don't want to take.  So we will need to do some careful thinking before we actually go and implement this.  

My advice for now is to make things as explicit as possible: maybe introduce a new "move" operator in addition to the "copy" operator, and just avoid using initializers for now.  Or something.  I'll keep thinking about this though, I'll let you know if I come up with something better.

**Comment by krame505** [comment]
After thinking about this a bit more, the best way forward in your case might actually be to use the Boehm GC library for memory allocation, similar to what we are doing in the vector extension.  Then you would be free to overload assignment and initialization to perform a copy, without needing to worry about deallocation.  This would still probably result in some unneeded copy operations, but that is probably OK for now.  You can try this out for now with just overloading assignment, and eventually also overloading initialization when I get around to implementing this should be straightforward.

**Comment by ericvanwyk** [comment]
Hi Lucas,  We decided to not use the GC library for performance reasons.
Once we start really caring about performance this becomes a less
interesting option.  For parallel programming extensions we want to get the
best performance possible.  The GC lib also doesn't seem to play well with
valgrind for looking for memory issues.  -Eric

**Comment by counc009** [comment]
Currently, we have the extension working (with careful malloc's and free's), at least when used carefully. So this issue isn't as much about getting the extension to work, it's more a feature idea to look into.
