### ISSUE TITLE
Array Subscript assign in new overloading

### ISSUE THREAD

**Issue by counc009** [melt-umn/ableC#131]
With the old overloading method, it was possible to overload array subscript assignments (so A[x] = ... ). I was wondering if there's a method of doing this with the new overloading? For the tensor algebra extension, this is relevant because there is different behavior if we are assigning a value to a specific index of a tensor, instead of accessing a value out of a tensor. Thanks for the help.

**Comment by krame505** [comment]
Yes, this is an omission, since at the time of redesigning overloading I assumed that any more "interesting" assignment overloads could be done via overloading the `&` operator and using the "derived" overload.  Here that is clearly not the case.  I'll try to add that functionality soon when I get a chance.
