### ISSUE TITLE
Missing Errors on break and continue

### ISSUE THREAD

**Issue by counc009** [melt-umn/ableC#184]
Currently we have don't produce errors if a break is placed outside of a loop/switch statement or if a continue is placed outside of a loop. I don't think this would be too hard to fix, we could introduce two new boolean attributes to just track whether a break/continue is valid and produce appropriate error messages when we encounter a break/continue when the associated attribute is false. 
These attributes probably gets placed on the same nonterminals as `returnType`, and they will generally just be copied from parent to child with loops setting them both to true and switch statements setting the attribute for break to true. (I'll try to check the C standard just to make sure there are no other caveats to their usage)

I may get around to this sometime during this semester, if not I put a reminder on my phone for May so I'll eventually get around to this.

**Comment by krame505** [comment]
Thanks, that would be nice.  

You *probably* just need those attributes on `Stmt`, since I don't think it is legal to have a `break` or `continue` inside an expression.  You should probably check that, but it's probably fine if you don't initially permit that to avoid having to add the attributes on a large number of nonterminals.

**Comment by remexre** [comment]
tragically, GCC seems to allow

```
int main(void) {
  switch (3) {
  case 3:
    ({ break; });
  }
  return 0;
}
```

so I think it'd need to be on Expr for stmtexprs
