### ISSUE TITLE
Merge returnType, breakValid, continueValid into one attribute

### ISSUE THREAD

**Issue by counc009** [melt-umn/ableC#186]
With the introduction of `breakValid` and `continueValid` attributes (#185) this increases the number of attributes we have to decorate expressions, statements, etc. with and it would probably be nicer and cleaner to merge these all into one attribute, like `controlStmtContext`. The nicest implementation might be for this to have a nonterminal type with an empty flow-type and attributes for `returnType`, `breakValid`, and `continueValid` (we could maybe even make it a closed nonterminal to allow other attributes to be added, though I don't know how useful that would really be).

I would also propose that if we do this it might be worth discussing whether we could/should move labels out of the environment and try to move them onto something like this since labels and gotos are control-flow mechanisms. Basically, if we put the list of labels on this attribute it would be easier to drop all labels inside some new construct (and therefore cause errors if code tries to use a `goto` to some label declared outside of the extension construct). This would allow extensions to introduce new constructs that could provide more guarantees about appropriate control-flow, which might be nice from a correctness perspective.

Self-assigning, and I'll try to get around to this towards the end of the semester.

**Comment by ericvanwyk** [comment]
This sounds like a good idea to me.  Don't labels and regular names have different scoping rules since labels can be used, I presume, before they are "declared" but names do not have this property.  This makes me wonder how labels are handled in the current environment?

**Comment by krame505** [comment]
Label defs are currently collected in the `functionDefs` attribute on `Stmt`, containing all defs that should be visible for the entire function body - the `functionDecl` production adds all `functionDefs` from its body `Stmt` to the `env` that is given to the body.  

I suppose that labels could get moved out of the environment, since extensions might want to pass down a different label environment than the rest of the `env`.  This is probably a bug in the closure extension actually, since labels in the outer function are visible inside a lambda expression body, which isn't valid as lambda bodies are lifted into seperate global functions.
