### ISSUE TITLE
Error-reporting of line numbers off by number of comments lines?

### ISSUE THREAD

**Issue by remexre** [melt-umn/ableC#51]
To reproduce:

```
git clone git@github.umn.edu:melt/ableC-tensors.git
cd ableC-tensors
git checkout 4050ac2
cd test
make
java -jar ../examples/ableC.jar test.xc -I ../include
```

The error is on line 32 (using a function-call-like concrete production `ones` in a declaration), but ableC reports it as being on line 25.

**Comment by krame505** [comment]
Yeah, this is somewhat buggy, but nobody has had time to look. Probably
related to ableC's handling of CPP tags, I would start by trying to
reproduce this in a file without includes.

On Jun 26, 2017 1:30 PM, "Nathaniel Ringo" <notifications@github.com> wrote:

To reproduce:

git clone git@github.umn.edu:melt/ableC-tensors.git
cd ableC-tensors
git checkout 4050ac2
cd test
make
java -jar ../examples/ableC.jar test.xc -I ../include

The error is on line 32 (using a function-call-like concrete production ones
in a declaration), but ableC reports it as being on line 25.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/melt-umn/ableC/issues/51>, or mute the thread
